### PR TITLE
PEP8 and other minor fixes

### LINKED ISSUE #4: PEP8
My code has not obeyed PEP8...

### PR DESCRIPTION
**Pull request by delirious-lettuce**
Fixes #4

### CODE REVIEW

**Review by rarewin — CHANGES_REQUESTED** [review]
Thank you for your PEP8 patch.
Thank you for your corrections of my typos as well.

However, I would like to request change on one thing.
Would you mind returning some class names in "atom.py"?
Although you capitalized the classes, ftyp, moov, mvhd, tkhd, mdhd, and elst according to PEP8, this change seems to make the result incorrect.

Sorry for my lack of test.

**Comment by delirious-lettuce** [comment]
@rarewin ,

I reverted the class names to lowercase, hopefully that fixes the issue!

**Comment by rarewin** [comment]
This works completely!
Thank you!

**Comment by delirious-lettuce** [comment]
@rarewin ,

No problem, thanks for your time!

**Pull request merged**
